---
title: mb bischoff
timezone: America/New_York
collections:
  category:
    title: Categories
    output: true
  formats:
    title: Formats
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
    description: ''
    format: post
    thanks: 
    link: 
    audio:
      title: 
      link: 
    picture:
      webp_image: 
      jpeg_image: 
      png_image: 
      width: 
      height: 
      alt: 
- scope:
    path: ''
    type: category
  values:
    layout: category
description: mb makes apps, posts, and podcasts. this is under construction.
permalink: "/:title/"
url: https://mbbischoff.com
paginate: 5
baseurl: 
author:
  name: mb bischoff
  url: https://twitter.com/mb
  email: mb@mbbischoff.com
  twitter: mb
logo: "/uploads/matthew.jpeg"
version: 3
license:
  copyright: 
    >
     2024 <span class="full-name">mb bischoff</span>
  text: Some rights reserved
  url: http://creativecommons.org/licenses/by-sa/4.0/
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-feed
- jekyll-redirect-from
twitter:
  username: mb
facebook:
  publisher: https://www.facebook.com/matthewbischoff
  admins: https://www.facebook.com/matthewbischoff
google_site_verification: XK_j6lkDAd8qOhIn4-2eS2BIJuQyRp4D_gxjpR65wUM
repository: mattbischoff/website
header:
  title: mb
  subtitle: <span class="full-name"">mb bischoff</span> makes <a href="https://lickability.com">apps</a>,
    <a href="/archive/">words</a>, & <a href="https://absolutelycrushed.com">sounds</a>. this is <a href="/under-construction/">under construction</a>.

navigation_links:
- title: Home
  url: "/"
  icon: fa-house
  selected_icon: fa-house
- title: About
  url: "/about/"
  icon: fa-circle-user
  selected_icon: fa-circle-user
- title: Archive
  url: "/archive/"
  icon: fa-archive
  selected_icon: fa-archive
- title: Contact
  url: "/contact/"
  icon: fa-comment-dots
  selected_icon: fa-comment-dots
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
