---
title: mb bischoff
timezone: America/New_York
collections:
  category:
    title: Categories
    output: true
  formats:
    title: Formats
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
    description: ''
    format: post
    color: 
    link: 
    audio:
      title: 
      link: 
    picture:
      webp_image: 
      jpeg_image: 
      png_image: 
      width: 
      height: 
      alt: 
- scope:
    path: ''
    type: category
  values:
    layout: category
description: mb makes software at Lickability. They also write, speak, and play.
permalink: "/:title/"
url: https://mbbischoff.com
paginate: 5
baseurl: 
author:
  name: mb bischoff
  url: https://twitter.com/mb
  email: mb@matthewbischoff.com
  twitter: mb
logo: "/uploads/matthew.jpeg"
version: 3
license:
  copyright: " 2024 mb bischoff."
  text: Some rights reserved.
  url: http://creativecommons.org/licenses/by-sa/4.0/
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-feed
- jekyll-redirect-from
twitter:
  username: mb
facebook:
  publisher: https://www.facebook.com/matthewbischoff
  admins: https://www.facebook.com/matthewbischoff
google_site_verification: XK_j6lkDAd8qOhIn4-2eS2BIJuQyRp4D_gxjpR65wUM
repository: mattbischoff/matthewbischoff.com
header:
  title: mb bischoff
  subtitle: mb run Lickability. They also write, speak, and play. They are [under
    construction](/under-construction/).
navigation_links:
- title: Home
  url: "/"
- title: About
  url: "/about/"
- title: Archive
  url: "/archive/"
- title: Contact
  url: "/contact/"
- title: RSS
  url: "/feed/"
accent_color: "#000"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
